---
Name: mfa-bundle-routes
After:
  - '#rootroutes'
Except:
  envorconstant:
    - DISABLE_MFA_HELP
---
SilverStripe\Control\Director:
  rules:
    'mfa-help': 'Restruct\MFABundle\Controllers\MFAHelpController'